services:
  mariadb:
    image: mariadb:latest
    container_name: rr-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raterelay
      MYSQL_USER: raterelay_user
      MYSQL_PASSWORD: raterelay_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_init:/docker-entrypoint-initdb.d
    networks:
      - raterelay_network
  redis:
    image: redis:alpine
    container_name: rr-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis_secure_password
    command: ["redis-server", "--requirepass", "redis_secure_password"]
    networks:
      - raterelay_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_secure_password", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  raterelay_network:
    driver: bridge

volumes:
  mariadb_data:
  mariadb_init:
