ALTER TABLE business_reviews
ADD COLUMN Rating TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER Status,
ADD COLUMN Comment VARCHAR(512) NOT NULL DEFAULT '' AFTER Rating,
ADD COLUMN PostedGoogleReview BOOL NOT NULL DEFAULT 0 AFTER Comment;
