name: Deploy Backend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4

      - name: Deploy backend
        run: |
          cd /root/raterelay-deployment
          
          cp -r $GITHUB_WORKSPACE/* backend/
          
          docker-compose build --no-cache backend
          docker-compose up -d backend nginx
          
          docker image prune -f